EsbLog.Web/Controllers/NavController.cs
using EsbLog.Web.Infrastructure;
using EsbLog.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace EsbLog.Web.Controllers
{
    [EsblogAuth]
    public class NavController : Controller
    {
        private readonly static List<NavViewModel> _navManageMenu
                                = new List<NavViewModel>();
        private readonly static List<NavViewModel> _navAppMenu
                                = new List<NavViewModel>();
        private static IEnumerable<NavViewModel> GetNavMenu(bool isManager)
        {
            if (_navManageMenu.Count == 0)
            {
                _navManageMenu.Add(new NavViewModel
                {
                    NavName = "首页",
                    ControllerName = "Home",
                    ActionName = "Index"
                });
                _navManageMenu.Add(new NavViewModel
                {
                    NavName = "应用管理",
                    ControllerName = "AppManage",
                    ActionName = "Index"
                });

                _navManageMenu.Add(new NavViewModel
                {
                    NavName = "权限管理",
                    ControllerName = "PermissionManage",
                    ActionName = "Index"
                });                
            }

            if (_navAppMenu.Count == 0)
            {
                _navAppMenu.Add(new NavViewModel
                {
                    NavName = "日志查询",
                    ControllerName = "Log",
                    ActionName = "Index"
                });

                _navAppMenu.Add(new NavViewModel
                {
                    NavName = "扩展管理",
                    ControllerName = "Extension",
                    ActionName = "Index"
                });

                _navAppMenu.Add(new NavViewModel
                {
                    NavName = "报表管理",
                    ControllerName = "Report",
                    ActionName = "Index"
                });
            }
            if (isManager)
            {
                return _navManageMenu;
            }
            else
            {
                return _navAppMenu;
            }
        }
        //
        // GET: /Nav/
        //public ActionResult Menu(string selectedNav = null)
        //{
        //    ViewBag.SelectedNav = selectedNav;
        //    ViewBag.UserName = this.User.Identity.Name;
           
        //    return PartialView(GetNavMenu());
        //}
        [AllowAnonymous]
        [ChildActionOnly]
        public ActionResult MatrixMenu(ViewContext context)
        {
            var controller = context.RouteData.Values["controller"].ToString();
            
            var user = context.HttpContext.Session["User"] as UserSessionModel;
           
            var menuList = GetNavMenu(user.IsManager);
            foreach (var m in menuList)
            {
                m.IsActive = string.Equals(m.ControllerName, controller, StringComparison.OrdinalIgnoreCase);
            }
            return PartialView(menuList);
        }
        [AllowAnonymous]
        public ActionResult MatrixContentHeader(RouteData routeData) 
        {
            var model = new ContentHeaderDisplayViewModel();
            model.Headers = EsblogConfig.ContentHeaders
                            .Where(c => c.ControllerName.ToUpper() 
                                    == routeData.Values["controller"].ToString().ToUpper());
            model.RouteValues = routeData.Values;
            return PartialView(model);
        }
	}
}

EsbLog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    @Html.Action("Menu", "Nav", new { selectedNav = this.ViewContext.RouteData.Values["controller"].ToString() })
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav"> 
                    <li></li>
                </ul>
            </div>
        </div>
    </div>*@

    <div class="container theme-showcase" role="main">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

EsbLog.Web/Views/Shared/_MatrixLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/Content/Matrix/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/Matrix/css/bootstrap-responsive.min.css" />

    <link href="~/Content/Matrix/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/Matrix/css/matrix-style.css" />
    <link rel="stylesheet" href="~/Content/Matrix/css/matrix-media.css" />
    <title>@ViewBag.Title</title>
    @RenderSection("css",false)
    @*<link rel="stylesheet" href="~/Content/Matrix/css/colorpicker.css" />
    <link rel="stylesheet" href="~/Content/Matrix/css/datepicker.css" />
    <link rel="stylesheet" href="~/Content/Matrix/css/uniform.css" />
    <link rel="stylesheet" href="~/Content/Matrix/css/select2.css" />

    <link rel="stylesheet" href="~/Content/Matrix/css/bootstrap-wysihtml5.css" />*@
    
</head>
<body>

    <!--Header-part-->
    <div id="header">
        <h3 style="padding-left:10px">统一日志管理平台</h3>
    </div>
    <!--close-Header-part-->
    <!--top-Header-menu-->
    <div id="user-nav" class="navbar navbar-inverse">
        <ul class="nav">
            <li class="dropdown" id="profile-messages">
                <a title="" href="#" data-toggle="dropdown" data-target="#profile-messages" class="dropdown-toggle">
                    <i class="icon icon-user"></i>  
                    <span class="text">欢迎您,@this.User.Identity.Name</span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    @*<li><a href="#"><i class="icon-user"></i> My Profile</a></li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-check"></i> My Tasks</a></li>
                    <li class="divider"></li>*@
                    <li><a href="@Url.Action("EditPsw", "Account")"><i class="icon-key"></i> 密码修改</a></li>
                    <li><a href="@Url.Action("Logout", "Account")"><i class="icon-chevron-right"></i> 注 销</a></li>
                </ul>
            </li>
            @*<li class="dropdown" id="menu-messages">
                <a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="icon icon-envelope"></i> <span class="text">Messages</span> <span class="label label-important">5</span> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a class="sAdd" title="" href="#"><i class="icon-plus"></i> new message</a></li>
                    <li class="divider"></li>
                    <li><a class="sInbox" title="" href="#"><i class="icon-envelope"></i> inbox</a></li>
                    <li class="divider"></li>
                    <li><a class="sOutbox" title="" href="#"><i class="icon-arrow-up"></i> outbox</a></li>
                    <li class="divider"></li>
                    <li><a class="sTrash" title="" href="#"><i class="icon-trash"></i> trash</a></li>
                </ul>
            </li>
            <li class=""><a title="" href="#"><i class="icon icon-cog"></i> <span class="text">Settings</span></a></li>
            <li class=""><a title="" href="login.html"><i class="icon icon-share-alt"></i> <span class="text">Logout</span></a></li>*@
        </ul>
    </div>

    <!--start-top-serch-->
    @*<div id="search">
        <input type="text" placeholder="Search here..." />
        <button type="submit" class="tip-bottom" title="Search"><i class="icon-search icon-white"></i></button>
    </div>*@
    <!--close-top-serch-->

    <!--sidebar-menu-->
    @Html.Action("MatrixMenu", "Nav", new { context = this.ViewContext })
    <!--close-left-menu-stats-sidebar-->

    <div id="content">
        @*<div id="content-header">            
                <div id="breadcrumb">
                    @Html.Action("MatrixContentHeader", "Nav", new { RouteData = this.ViewContext.RouteData })
                </div>
                <h1>@RenderSection("ContentHeader",false)</h1>
        </div>*@
        <div class="container-fluid">
            @*<hr>*@
            @RenderBody()           
        </div>
    </div>

    <!--Footer-part-->
    <div class="row-fluid">
        <div id="footer" class="span12"> 2017 &copy; 统一日志管理平台 </div>
    </div>
    <!--end-Footer-part-->

    <script src="~/Content/Matrix/js/jquery.min.js"></script>
    <script src="~/Content/Matrix/js/jquery.ui.custom.js"></script>
    <script src="~/Content/Matrix/js/bootstrap.min.js"></script>
    <script src="~/Content/Matrix/js/matrix.js"></script>
    @*<script src="~/Content/Matrix/js/matrix.form_common.js"></script>*@
    @*<script src="~/Content/Matrix/js/bootstrap-colorpicker.js"></script>
    <script src="~/Content/Matrix/js/bootstrap-datepicker.js"></script>
    <script src="~/Content/Matrix/js/jquery.toggle.buttons.js"></script>
    <script src="~/Content/Matrix/js/masked.js"></script>
    <script src="~/Content/Matrix/js/jquery.uniform.js"></script>
    <script src="~/Content/Matrix/js/select2.min.js"></script>
    
    <script src="~/Content/Matrix/js/wysihtml5-0.3.0.js"></script>
    <script src="~/Content/Matrix/js/jquery.peity.min.js"></script>
    <script src="~/Content/Matrix/js/bootstrap-wysihtml5.js"></script>
    <script>
        $('.textarea_editor').wysihtml5();
    </script>*@
    @RenderSection("scripts",false)
</body>
</html>