EsbLog.Web/Controllers/AppManageController.cs
using EsbLog.Web.Repository;
using EsbLog.Domain.Platform;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NLog;
using EsbLog.Web.Infrastructure;

namespace EsbLog.Web.Controllers
{
    [EsblogAuth]
    public class AppManageController : Controller
    {
        private static Logger _logger = LogManager.GetCurrentClassLogger();
        IAppManagerRepository _repo;
        public AppManageController(IAppManagerRepository repo)
        {
            _repo = repo;

        }

        //
        // GET: /AppManage/
        public ActionResult Index()
        {
            return View(_repo.FindAllApps());
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(App app)
        {
            if (ModelState.IsValid)
            {
                app.PublicKey = Guid.NewGuid().ToString();
                _repo.AddApp(app);
                return RedirectToAction("Edit", new { id = app.AppId });
            }
            return View(app);
        }

        public ActionResult Edit(int id)
        {
            var app = _repo.FindAllApps().FirstOrDefault(a => a.AppId == id);
            if (app == null)
            {
                return RedirectToAction("Add");
            }
            else
            {
                return View(app);
            }
        }

        [HttpPost]
        public ActionResult Edit(App app)
        {
            bool isSuccess = false;

            if (ModelState.IsValid)
            {
                isSuccess = _repo.EditApp(app);                
            }
            TempData.Add("success", isSuccess);
            
            return View(app);
            //else
            //{
            //    return RedirectToAction("Edit", new { id = app.AppId });
            //}
        }
	}
}

EsbLog.Web/Controllers/ExtensionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EsbLog.Web.Controllers
{
    public class ExtensionController : Controller
    {
        //
        // GET: /Extension/
        public ActionResult Index()
        {
            return View();
        }
	}
}

EsbLog.Web/Controllers/HomeController.cs
using EsbLog.Web.Models;
using EsbLog.Web.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace EsbLog.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        IAccountRepository _repo;
        IAppManagerRepository _appRepo;
        public HomeController(IAccountRepository repo, IAppManagerRepository appRepo)
        {
            _repo = repo;
            _appRepo = appRepo;
        }
        //
        // GET: /Home/
        public ActionResult Index()
        {
            int? id = Session["id"] as int?;
            if (!id.HasValue)
            {
                return RedirectToAction("Login", "Account", new { returnUrl = Request.RawUrl });                
            }
            else
            {
                var user = _repo.FindUserById(id.Value);
                HomeModel m = new HomeModel();
                m.IsManager = user.UserType.ToLower() == "m";
                if (m.IsManager)
                {
                    m.AppCount = _appRepo.GetCount();
                    m.PermissionCount = _repo.GetCount();
                    return View(m);
                }
                else
                {
                    return RedirectToAction("Index","Log");
                }                
            }            
        }

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(); 
        }
                
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(LoginUserViewModel user,string returnUrl)
        {
            int userId = _repo.ValidateUser(user.UserName, user.Password);
            if (userId>0)
            {
                //Session["User"] = user;
                _repo.UpdateLoginTime(userId);
                FormsAuthentication.SetAuthCookie(user.UserName, false);
                return Redirect(string.IsNullOrEmpty(returnUrl)
                                    ? Url.Action("Index", "Account")
                                    : returnUrl);
            }
            else
            {
                ModelState.AddModelError("", "用户名或者密码错误");
                return View();
            }
            
            //return Content(string.Format("{0},{1},{2}",user.UserName,user.Password,user.RememberMe));
        }

        [AllowAnonymous]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            //Session["User"] = null;
            return RedirectToAction("Login");
        }
	}
}

EsbLog.Web/Controllers/PermissionManageController.cs
using AutoMapper;
using EsbLog.Domain.Platform;
using EsbLog.Web.Infrastructure;
using EsbLog.Web.Models;
using EsbLog.Web.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EsbLog.Web.Controllers
{
    [EsblogAuth]
    public class PermissionManageController : Controller
    {
        IAppManagerRepository _appRepo;
        IPermissionRepository _perRepo;
        IAccountRepository _accountRepo;
        public PermissionManageController(IAppManagerRepository appRepository,
                IAccountRepository accountRepo)
        {
            _appRepo = appRepository;
            _accountRepo = accountRepo;
        }

        // GET: /Permission/
        public ActionResult Index()
        {
            var appLoginUsers = _accountRepo.FindUsers();

            return View(appLoginUsers);
        }

        [HttpPost]
        public ActionResult Index(PermissionQueryRequest queryRequest)
        {
            var apploginUsers = _accountRepo.FindUsers()
                                .Where(u => string.IsNullOrEmpty(queryRequest.UserName)
                                        || u.LoginName.Contains(queryRequest.UserName));

            return View(apploginUsers);
        }

        public ActionResult Add()
        {
            var applist = _appRepo.FindAllApps();
            //.Where(a => a.Users == null);
            LoginUserEditModel model = new LoginUserEditModel
            {
                AppList = applist
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Add(LoginUserEditModel addModel)
        {
            var loginUser = Mapper.Map<LoginUser>(addModel);
            bool success = _accountRepo.AddUser(loginUser);
            addModel.Id = loginUser.Id;
            TempData["success"] = success;
            return RedirectToAction("Edit", new { id = addModel.Id });
        }

        public ActionResult Edit(int id)
        {
            var user = _accountRepo.FindUserById(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var loginUser = Mapper.Map<LoginUserEditModel>(user);
            loginUser.AppList = _appRepo.FindAllApps();
            return View("Add", loginUser);
        }

        [HttpPost]
        public ActionResult Edit(LoginUserEditModel user)
        {
            var loginUser = Mapper.Map<LoginUser>(user);
            bool success = _accountRepo.EditUser(loginUser);

            TempData["success"] = success;
            return RedirectToAction("Edit", new { id = user.Id });
        }
    }
}

EsbLog.Web/Views/Home/Index.cshtml
@model EsbLog.Web.Models.HomeModel
@{
    ViewBag.Title = "Index";
}


<div class="container-fluid">
    <div class="quick-actions_homepage">
        <ul class="quick-actions">
            <li class="bg_ly span3"> <a href="@Url.Action("Index","AppManage")"> <i class="icon-key"></i> <span class="label label-important">@Model.AppCount</span> 应用管理 </a> </li>
            <li class="bg_lg span3"> <a href="@Url.Action("Index", "PermissionManage")"> <i class="icon-lock"></i><span class="label label-warning">@Model.PermissionCount</span> 权限管理</a> </li>
            @*<li class="bg_ly span3"> <a href="@Url.Action("Index", "Extension")"> <i class="icon-cogs"></i> 扩展管理 </a> </li>*@
        </ul>
    </div>
</div>



EsbLog.Web/Views/Home/Login.cshtml
@model EsbLog.Web.Models.LoginUserViewModel
@{
    Layout = null;
    ViewBag.Title = "Login";
}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/Content/signin.css" rel="stylesheet">
    @*<script src="~/Scripts/modernizr-2.6.2.js"></script>*@
</head>
<body>
    <div class="container">
        @using (Html.BeginForm("Login", "Home", FormMethod.Post, new { @class = "form-signin" }))
        {
             <h2 class="form-signin-heading">统一日志管理平台</h2>
            <label for="inputEmail" class="sr-only">邮箱</label>
            
            <input type="email" id="UserName" name="UserName" class="form-control" placeholder="邮箱" required autofocus>
            <label for="inputPassword" class="sr-only">密码</label>
            <input type="password" id="Password" name="Password" class="form-control" placeholder="密码" required>
            @Html.Hidden("returnUrl", (string)ViewBag.ReturnUrl);
            @Html.ValidationSummary(true,"", new { @class = "alert alert-danger" })
            <div class="checkbox">
                <label>
                    <input type="checkbox" id="RememberMe" value="remember-me">记住我
                </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">登 录</button>
        }

    </div> 
</body>
</html>
